# Generated by Django 4.2.5 on 2024-01-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_alter_reservacion_usuario_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='fecha_registro',
        ),
    ]
