# Generated by Django 4.2.5 on 2024-02-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0005_alter_reservacion_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
