# Generated by Django 4.2.7 on 2023-11-19 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='tipoHabitacion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField()),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('numero', models.CharField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('info_add', models.CharField(max_length=500)),
                ('fecha_registro', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Habitaciones.tipohabitacion')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
