# Generated by Django 4.2.5 on 2023-11-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='tipo',
            new_name='id_tipo',
        ),
    ]
