# Generated by Django 4.2.5 on 2023-11-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0002_rename_tipo_habitacion_id_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
