# Generated by Django 4.2.5 on 2024-01-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0004_alter_habitacion_usuario_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='usuario_registro',
        ),
    ]
