# Generated by Django 4.2.5 on 2024-01-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0005_remove_tipohabitacion_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='fecha_registro',
        ),
    ]
