# Generated by Django 4.2.5 on 2024-01-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0006_remove_habitacion_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='fecha_registro',
            field=models.DateTimeField(default='2012-08-23'),
        ),
    ]
