# Generated by Django 4.2.5 on 2024-01-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0007_habitacion_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
