# Generated by Django 4.2.5 on 2024-01-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0008_alter_habitacion_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='precio',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
