# Generated by Django 4.2.7 on 2023-11-19 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='huesped',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('CI', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=8)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
