# Generated by Django 4.2.5 on 2024-01-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Huespedes', '0006_alter_huesped_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
